version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/myproject
    ports:
      - 8000:8000
    image: app:myproject
    container_name: myproject_container
    command: python manage.py runserver 0.0.0.0:8000



